#!/bin/sh
# Set up Android SDK path
echo "sdk.dir=$HOME/Library/Android/sdk" > android/local.properties

# Set up iOS node binary path only
echo 'export NODE_BINARY=$(command -v node)' > ios/.xcode.env.local